---
title: "01_data"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# read in data from pgAdmin
```{r loading data}
rm(list = ls())

# load packages 
for (pkg in c("tidyverse", "igraph", "visNetwork", "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr", "stringr", "stringi", "mosaic", "regex")) {
  library(pkg, character.only = TRUE)
}


# connect to postgresql to get our data
conn <- dbConnect(drv = PostgreSQL(), 
                  dbname = "sdad", 
                  host = "10.250.124.195", 
                  port = 5432, 
                  user = Sys.getenv("db_userid"), 
                  password = Sys.getenv("db_pwd"))

# query the users_gh data from github data 
users_gh <- dbGetQuery(conn, "SELECT login, created_at, city, state, country_code, location, long, lat
                              FROM gh.ctrs_raw")

cities_maxmind <- dbGetQuery(conn, 
"SELECT *
  FROM maxmind.world_cities"
)

# too large to read in the raw commit data. Will crash R
# commits <- dbGetQuery(conn,
#                       "SELECT *
#                       FROM gh.commits_raw")

# disconnect from postgresql database 
dbDisconnect(conn)
```

# data cleaning
```{r}
# 1. github user

# check: users who don't have any of city, state, location, long, lat, don't have country code
# user_geo_na <- users_gh %>%
#   filter(is.na(state))%>%
#   filter(is.na(city))%>%
#   filter(is.na(location))%>%
#   filter(is.na(long), is.na(lat))
# table(is.na(user_geo_na$country_code)) #all users have country code

# filter out users with no country/city
sum(is.na(users_gh$country_code))/nrow(users_gh) #percent missing

users_gh_clean <- users_gh%>%
  filter(!is.na(country_code))

# some users who are missing country code have cities, but cities might not be reliable
users_gh_countrycode_na <- users_gh%>%
  filter(is.na(country_code))

# check: users created year
class(users_gh$created_at) 
users_gh_clean <- users_gh_clean %>%
  mutate(created_year = substring(created_at, 1,4)) #extract year from the date
table(users_gh_clean$created_year)

# 2. world cities
cities_maxmind_clean <- cities_maxmind%>%
  mutate(city_code  = paste(Country, City, sep="_"))%>%
  mutate(long = round(Longitude, digits=0), lat = round(Latitude, digits=0))

cities_maxmind_clean$city_code <- str_replace_all(cities_maxmind_clean$city_code, fixed(" "), "")
```

# 
1. long, lat from gh_users are not reliable, we are going to use the info from world cities from maxmind instead. Ex. Paris, France' long lat from gh gives us 
```{r}
# glimpse(cities_maxmind)
# table(cities_maxmind$Country)

users_gh_us <- users_gh_clean %>%
  filter(city == "shanghai")

city_summary <- users_gh_clean%>%
  filter(!is.na(city))%>%
  mutate(city = str_to_lower(city)) %>%
  mutate(user_long = round(long,digits=0), user_lat = round(lat, digits=0))%>%
  group_by(country_code, city, user_long, user_lat)%>%
  summarize(ttl_users = n())%>%
  arrange(desc(ttl_users))%>%
  filter(!is.na(city))%>%
  mutate(city_code  = paste(country_code, city, sep="_"))
city_summary$city_code <- str_replace_all(city_summary$city_code, fixed(" "), "")

cleancity <- function(df = city_summary){
  # create an indicator for each row whether the city code is duplicated
  df <- df%>%
    group_by(city_code)%>%
    mutate(n_city_code=n(), duplicate = if_else(n_city_code > 1, T,F))
  
  # data with duplicated city code
  df_dup <- df%>%
    filter(duplicate == T)
  
  # data with no duplicated city code
  df_no_dup <- df%>%
    filter(duplicate == F)
  
  # duplicated city code vector
  city_code <- unique(df_dup$city_code)
  
  i=3
  for ( i in 1: length(city_code)){
    city_code_i = city_code[i]
    df_dup_i <- df_dup %>%
      filter(city_code == city_code_i)
    user_long_i <- df_dup_i$user_long
    user_lat_i <- df_dup_i$user_lat
    
    df_dup_i
  }
  
  
  
}

  


city_sumary_info <- left_join(city_summary, cities_maxmind_clean, by = "city_code")
```

# topusers
```{r}
# topuser <- commits%>%
#   group_by(login)%>%
#   dplyr::summarize(ttl_commit = n(), .groups = "keep")%>%
#   arrange(desc(ttl_commit))%>%
#   top_n(n= 10)
```

# users by country
```{r}
# summarize ttl number of users in each country
country_by_ttl_user <- users_gh_clean%>%
  group_by(country_code)%>%
  dplyr::summarize(ttl_users = n())%>%
  arrange(desc(ttl_users))

```

