---
title: "02 Email Domain Search"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r loading data, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
rm(list = ls())

# load packages 
for (pkg in c("tidyverse", "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr", "stringr", "stringi", "mosaic",  "raster", "dplyr",  "ggplot2", "shiny", "plotly", "gt", "glue")) {
  library(pkg, character.only = TRUE)
}


# connect to postgresql to get our data
conn <- dbConnect(drv = PostgreSQL(), 
                  dbname = "sdad", 
                  host = "10.250.124.195", 
                  port = 5432, 
                  user = Sys.getenv("db_userid"), 
                  password = Sys.getenv("db_pwd"))

gh_extra <- dbGetQuery(conn, "SELECT *
                              FROM gh.ctrs_extra")

# disconnect from postgresql database 
dbDisconnect(conn)
```


```{r message=FALSE, warning=FALSE, paged.print=FALSE}
email_clean <- gh_extra%>%
  filter(!is.na(email))

#domain
email_clean %>%
  mutate(email_domain =  str_extract(email_clean$email, "@[a-z]+"))%>%
  group_by(email_domain)%>%
  summarize(N = n())%>%
  arrange(desc(N))%>%
  top_n(20, N)%>%
  gt()%>%
   tab_header(
    title = "Top Github User Email Domains"
  )


#edu email
table(grepl("edu", email_clean$email))

email_clean %>%
  mutate(edu = if_else( str_detect( email, "edu$") == T, T, F))%>%
  filter(edu == T)%>%
  mutate(institution =  str_extract(email, "@[a-z]+"))%>%
  mutate(institution_full = str_extract(email, "@(.*)edu"))%>%
  select(login, email, institution,institution_full)%>%
  group_by(institution_full)%>%
  summarize(N = n())%>%
  arrange(desc(N))%>%
  top_n(50,N)%>%
  gt()%>%
   tab_header(
    title = "Top Github User Institutional Email Domains"
  )

```

