---
title: "email-cleaning"
author: "Morgan Klutzke"
date: "6/23/2020"
output: html_document
---

```{r packages}
rm(list = ls())

# load packages 
for (pkg in c("tidyverse", "igraph", "visNetwork", "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr", "stringr", "stringi")) {library(pkg, character.only = TRUE)}
```

```{r loading data}
# connect to postgresql to get our data
conn <- dbConnect(drv = PostgreSQL(), 
                  dbname = "sdad", 
                  host = "10.250.124.195", 
                  port = 5432, 
                  user = Sys.getenv("db_userid"), 
                  password = Sys.getenv("db_pwd"))

# query the users_gh data from github data 
users_gh <- dbGetQuery(conn, "SELECT email, company
                              FROM gh.ctrs_extra")

institutions_hipolabs <- dbGetQuery(conn, "SELECT institution, domains FROM hipolabs.universities")
```

```{r}
# disconnect from postgresql database 
dbDisconnect(conn)
```

Boosting university counts by looking at email domains

```{r}
# Getting just the domains for GitHub users' emails
email_domains <- users_gh %>% drop_na(email) %>%
dt_mutate(domains = str_replace_all(email, "^[a-zA-Z0-9_.+-]+@", ""))

domain_count <- email_domains %>% group_by(domains) %>% count() %>% arrange(-n)
domain_count
```

```{r}
# Looking at domains present in both GitHub and hipolabs data
email_domains <- as.data.table(email_domains)
email_overlap <- inner_join(email_domains, institutions_hipolabs)
email_overlap
```

Matching the institutions from hipolabs to GitHub users based on email domains

```{r}
institutions_hipolabs <- as.data.table(institutions_hipolabs)

setkey(institutions_hipolabs, "domains")
setkey(email_domains, "domains")

join <- institutions_hipolabs[email_domains]
join
```



```{r}
length(drop_na(join, institution)$institution)
# inferred institutions for 17514 users
```

