---
title: "Company Counts on GitHub"
author: "Brandon L. Kramer"
date: "11/26/2019"
output: html_document
---

```{r loading data}
rm(list = ls())

# load packages 
for (pkg in c("tidyverse", "igraph", "visNetwork", "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr", "stringr", "stringi")) {library(pkg, character.only = TRUE)}

# connect to postgresql to get our data
conn <- dbConnect(drv = PostgreSQL(), 
                  dbname = "sdad", 
                  host = "10.250.124.195", 
                  port = 5432, 
                  user = Sys.getenv("db_userid"), 
                  password = Sys.getenv("db_pwd"))

# query the users_gh data from github data 
users_gh <- dbGetQuery(conn, "SELECT * 
                              FROM gh.ctrs_extra")

# disconnect from postgresql database 
dbDisconnect(conn)
```

```{r}

users_gh

length(users_gh$company) 
# 2,143,407 total entries 
# note: there are actually 2,435,698 total users

valid_company_codes <- users_gh %>% drop_na(company) 
length(valid_company_codes$company)
# 422517 users with some company_code information 
length(valid_company_codes$company) / length(users_gh$company)
# putting us at 19.7124% that are identifiable for now 

users_gh %>% 
  drop_na(company) %>% 
  mutate(organization = str_to_lower(company)) %>% 
  mutate(organization = str_trim(organization)) %>% 
  group_by(organization) %>% 
  count() %>% arrange(-n)

```

```{r company counts}
organization_counts <- users_gh %>% 
  drop_na(company) %>% 
  mutate(organization = str_to_lower(company)) %>% 
  mutate(organization = str_trim(organization)) %>% 
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(freelancer|freelance|freelancing|freelancers|freelances|self|personal|home|private|individual|myself|me|independent|independent contractor|contractor|private|household|house|home|my house|jobless|looking for a job|looking for job|seeking employment|seeking|actively seeking employment|seeking opportunities|seeking internship|seeking work)\\b"), 
                              yes = "household", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(n/a|none|null|no|na)\\b"),      
                              yes = "none/null", no = organization)) %>% 
  group_by(organization) %>% count() %>% arrange(-n) 

organization_counts 

```









